### PR TITLE
Added 1-5-0 release.

### PR DESCRIPTION
**Pull request by etagwerker**
Hey @DatabaseCleaner/owners,

I've released a new version of the gem and added an article about it.

Please check it out.

Thanks!

### CODE REVIEW

**Comment by claptimes5** [comment]
Did you want to mention: 

- https://github.com/DatabaseCleaner/database_cleaner/pull/376
- https://github.com/DatabaseCleaner/database_cleaner/pull/364 (mine)
- https://github.com/DatabaseCleaner/database_cleaner/pull/346

**Comment by JonRowe** [comment]
Not necessary to mention #376 thats an internal refactoring, possibly should mention #346 definitely should mention #364

**Comment by etagwerker** [comment]
@JonRowe @claptimes5 I just updated it with the missing PRs. Thanks for the heads up!

**Comment by JonRowe** [comment]
LGTM

**Pull request merged**
